$ANSIBLE_VAULT;1.1;AES256
64636631303061383064666463636233663666303534306362393364613634333136393334356365
6533366538613238356539613062343432386238373366350a636132333438313162343565656131
31313762343334303266643265643332643631643738363362366137366231656165386261373165
3061313135346564620a343065386534623135656466396566633563376261356236623261363430
34323266353566363461393362613237323661303564666535636631623130356464366263613762
62316633366662396238643636333332303161306338356536656634393637653436386636336162
30366265336433653663316265363930636139616233613561343334333663323663326538616263
36646430623661393538326561643732396339383166386339353466336664656137643432363461
30613031653134366131643339636336393666383764643539326266386165303766626463366135
35333036633435643430633565323965356164653133643831623132373732303934323638316261
36393662336637396637373134633336313437363236623065323737643637663138396334663931
38643439646433316236306466633430363033613336326363393132616435643130393032646638
66616532666365333536306639663564613638626531626632323061646336373738623232383739
3963613462373538333038303963393639363639643534383035
