#SPDX-License-Identifier: MIT-0
---
# vars file for webdb_infrastructure
# variables Debian
debian_packages:
  docker:
    - docker.io
    - python3-docker
  apache:
    - apache2
    - libapache2-mod-php
    - php
    - php-mysqli

debian_apache_service: "apache2"
debian_apache_config_path: "/etc/apache2/sites-available"
debian_apache_user: "www-data"

# variables Fedora
fedora_packages:
  docker:
    - docker
    - python3-docker
  apache:
    - httpd
    - php
    - php-mysqlnd

fedora_apache_service: "httpd"
fedora_apache_config_path: "/etc/httpd/conf.d"
fedora_apache_user: "apache"

